### ISSUE TITLE
TYPE_SIGNIFICANT_MOTION

### ISSUE THREAD

**Issue by argum** [GeraudBourdin/ti_sensor#2]
First, thanks for this awesome module for Titanium.

When this event will be fired? What is the conditions to fire it. I've tried but the event does not catch anything.

Thanks again.

**Comment by GeraudBourdin** [comment]
Hi ! You are right. There is a bug with significant motion sensor. I made a patch today, I will update the repo this weekend.  sorry for this ! :)

**Comment by GeraudBourdin** [comment]
For more info on this sensor. You have to know that to fire event you have to move enough to change your geolocation. I had to drive with my car to test my patch :) so it fire event when you walk  or drive bike or car etc.. it fire an event with a value of 1. you can have a look to the demo app for a code sample.

**Comment by GeraudBourdin** [comment]
Please use the 1.0.1 version, this should works as expected.  

https://github.com/GeraudBourdin/Ti.sensor/releases/download/1.0.1/com.geraudbourdin.sensor-android-1.0.1.zip

**Comment by argum** [comment]
Thanks Gerard!!

This module helps me so much. I will try it and back to you with my feedback.
